[package]
name = "qt-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = { version = "1.0.138", default-features = false, features = [ "alloc"] }
serde = { version = "1.0.217", default-features = false, features = ["derive", "alloc"] }
